### ISSUE TITLE
spotvol with milliseconds

### ISSUE THREAD

**Issue by kboudt** [onnokleen/highfrequency#12]
Current implementation requires at least seconds. 

> spotvol
function (data, method = "detper", ..., on = "minutes", k = 5, 
    marketopen = "09:30:00", marketclose = "16:00:00", tz = "GMT") 
{
    if (on == "seconds" | on == "secs") 
        delta <- k

**Comment by onnokleen** [comment]
spotDrift supports milliseconds now but kernel method of Christensen et al. 2018 is missing up to now

**Comment by onnokleen** [comment]
spotDrift now also with kernel estimation. Only one problem:

price <- sample_tdata$PRICE
storage.mode(price) <- "numeric"
kerneldrift <- spotDrift(price, method = "driftKernel", on = "minutes", k = 1)

Emil's code computes

formatC(kerneldrift$mu[1:6], digits = 5)
[1] "     0"    "-0.070876" "-0.1145"   "-0.072902" "0.020546"  "0.078481" 

However, the first entry is missing in my implementation:

formatC(kerneldrift$mu[1:6], digits = 5)
[1] "     0"    "-0.1145"   "-0.072902" "0.020546"  "0.078481"  "0.089241“ 

In contact with Emil regarding this issue
