### ISSUE TITLE
description file

### ISSUE THREAD

**Issue by kboudt** [onnokleen/highfrequency#13]
Hi Onno,

I propose you add yourself with the role "ctb", and that we mention Dirk in the thanks.

**Comment by onnokleen** [comment]
I will include Dirk in a "thanks"-section of an extended readme-file because I did not find a "thanks"-option for the DESCRIPTION file. I'll also include myself as a contributor if I am allowed to :)

**Comment by onnokleen** [comment]
I'll also include Emil Sjoerup for his pull request on harModel options.
