### ISSUE TITLE
rmOutliers

### ISSUE THREAD

**Issue by kboudt** [onnokleen/highfrequency#9]
The code for this function needs to be improved. I would also recommend that one can just input prices that one wants to clean using rolling median and mad. This is very effective to remove the price bounces.

**Comment by onnokleen** [comment]
Thanks for commenting, I think that would also be a good function to use data.table internally for large data sets!

**Comment by onnokleen** [comment]
Improvement done and now we have two functions, one for removing outliers in quotes (rmOutliersQuotes) and one for removing outliers in prices (rmOutliersPrices).
